### PR TITLE
bump build number

### PR DESCRIPTION
**Pull request by daler**
`argh` is not available on py36, hopefully bumping the build number will do the trick

### CODE REVIEW

**Comment by goanpeca** [comment]
@daler want to add yourself to the maintainers section ?

**Comment by daler** [comment]
Sure -- added.

**Comment by goanpeca** [comment]
@daler, you need to [rerender the recipe](https://github.com/conda-forge/conda-smithy), otherwise it will not work

**Comment by daler** [comment]
I'm totally unfamiliar with conda-forge infrastructure, thanks for the reminder and link.

**Comment by goanpeca** [comment]
Thanks a lot @daler :-), LGTM!

**Pull request merged**
